const STORAGE_KEY='novage_compras_demo_v1';
const seed={inventory:[
  {id:'INS-001',name:'Guantes de nitrilo',category:'Protección personal',stock:120,min:80,unit:'cajas',location:'Bodega clínica'},
  {id:'INS-002',name:'Jeringa estéril 10 ml',category:'Dispositivo médico',stock:34,min:60,unit:'unidades',location:'Sala de insumos'},
  {id:'INS-003',name:'Suero fisiológico 500 ml',category:'Solución clínica',stock:12,min:30,unit:'unidades',location:'Bodega clínica'},
  {id:'INS-004',name:'Apósito estéril 10 × 10',category:'Curación',stock:86,min:40,unit:'unidades',location:'Sala de procedimientos'},
  {id:'INS-005',name:'Mascarilla quirúrgica',category:'Protección personal',stock:200,min:100,unit:'unidades',location:'Bodega clínica'}
],suppliers:[
  {id:'PRV-001',name:'Proveedor Clínico Demo',category:'Insumos médicos',contact:'compras@example.invalid',status:'Verificación pendiente'},
  {id:'PRV-002',name:'Pineda · listado solicitado',category:'Catálogo por verificar',contact:'INFORMACION_NO_DISPONIBLE',status:'Pendiente documental'},
  {id:'PRV-003',name:'Logística Sanitaria Demo',category:'Distribución',contact:'operaciones@example.invalid',status:'Evaluación pendiente'}
],orders:[
  {id:'OC-0001',supplier:'Proveedor Clínico Demo',item:'Jeringa estéril 10 ml',itemId:'INS-002',quantity:50,unitCost:0,total:0,costCenter:'Operación clínica',reason:'Reposición por stock bajo · dato ficticio',status:'Solicitada',createdAt:new Date().toISOString(),owner:'Claudia Celedón'}
],audit:[{id:crypto.randomUUID(),type:'Sistema',message:'Entorno demostrativo inicializado',detail:'Datos ficticios · sin conexión operativa',actor:'Sistema',at:new Date().toISOString()}]};
let state=load();let integrations=[];
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0)}
function status(item){return item.stock===0?'critical':item.stock<item.min?'low':'ok'}
function badge(label,kind){return `<span class="badge ${kind}">${esc(label)}</span>`}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function audit(type,message,detail){state.audit.unshift({id:crypto.randomUUID(),type,message,detail,actor:'Claudia Celedón',at:new Date().toISOString()})}
function iconForCategory(cat){const c=cat.toLowerCase();if(c.includes('protección'))return'ph-shield';if(c.includes('solución'))return'ph-drop';if(c.includes('dispositivo'))return'ph-syringe';return'ph-first-aid-kit'}
const views={inicio:'Resumen ejecutivo',inventario:'Inventario clínico',ordenes:'Órdenes y aprobaciones',proveedores:'Proveedores controlados',trazabilidad:'Registro de auditoría',integraciones:'Chequeo de integraciones'};
function go(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));document.querySelector('#breadcrumb').textContent=views[view];history.replaceState(null,'',`#${view}`);document.querySelector('.sidebar').classList.remove('open');if(view==='integraciones')checkIntegrations()}
function renderMetrics(){const low=state.inventory.filter(i=>status(i)!=='ok').length;const pending=state.orders.filter(o=>o.status!=='Recibida').length;document.querySelector('#metrics').innerHTML=[['Artículos controlados',state.inventory.length,'ph-cube','Catálogo ficticio'],['Stock por revisar',low,'ph-warning-circle','Bajo mínimo'],['Órdenes abiertas',pending,'ph-shopping-cart-simple','Con aprobación humana'],['Proveedores',state.suppliers.length,'ph-buildings','Documentación pendiente']].map(x=>`<div class="metric"><div class="metric-top"><span>${x[0]}</span><i class="ph ${x[2]}"></i></div><strong>${x[1]}</strong><small>${x[3]}</small></div>`).join('')}
function renderInventoryPreview(){document.querySelector('#inventory-preview').innerHTML=state.inventory.slice(0,4).map(i=>`<div class="compact-row"><div class="item-name"><span class="item-icon"><i class="ph ${iconForCategory(i.category)}"></i></span><div><strong>${esc(i.name)}</strong><small>${esc(i.category)}</small></div></div><div><div class="stock-bar"><span style="width:${Math.min(100,i.stock/Math.max(i.min,1)*55)}%"></span></div><small>${i.stock} ${esc(i.unit)}</small></div>${badge(status(i)==='ok'?'Disponible':status(i)==='low'?'Stock bajo':'Crítico',status(i))}</div>`).join('')}
function renderOrderProgress(){const o=state.orders[0];if(!o){document.querySelector('#order-progress').innerHTML='<p>No hay órdenes activas.</p>';return}const steps=['Solicitada','Aprobada','Enviada','Recibida'],at=Math.max(0,steps.indexOf(o.status));document.querySelector('#order-progress').innerHTML=`<div class="progress-steps">${steps.map((s,i)=>`<div class="step ${i<at?'done':i===at?'active':''}"><i class="ph ${['ph-shopping-cart-simple','ph-clipboard-text','ph-truck','ph-check'][i]}"></i><small>${s}</small></div>`).join('')}</div><div class="order-summary"><strong>${esc(o.id)} · ${esc(o.item)}</strong><small>${esc(o.supplier)} · ${o.quantity} unidades</small></div>`}
function renderIntegrationPreview(){const base=integrations.length?integrations:[{name:'Gmail',configured:false,detail:'Chequeo pendiente'},{name:'Google Drive',configured:false,detail:'Chequeo pendiente'},{name:'Google Sheets',configured:false,detail:'Chequeo pendiente'}];document.querySelector('#integration-preview').innerHTML=base.slice(0,3).map(x=>`<div class="integration-item"><i class="ph ${x.icon||'ph-plug'}"></i><div><strong>${esc(x.name)}</strong><small>${esc(x.detail)}</small></div>${badge(x.configured?'Configurada':'Pendiente',x.configured?'ok':'low')}</div>`).join('')}
function renderSupplierPreview(){document.querySelector('#supplier-preview').innerHTML=state.suppliers.slice(0,3).map(s=>`<div class="supplier-mini"><strong>${esc(s.name)}</strong><small>${esc(s.category)}</small>${badge(s.status,s.status.includes('pendiente')||s.status.includes('Pendiente')?'low':'pending')}</div>`).join('')}
function renderInventory(){const q=document.querySelector('#inventory-search')?.value.toLowerCase()||'',f=document.querySelector('#inventory-filter')?.value||'all';const items=state.inventory.filter(i=>(f==='all'||status(i)===f)&&`${i.id} ${i.name} ${i.category}`.toLowerCase().includes(q));document.querySelector('#inventory-table').innerHTML=`<div class="table-row header"><span>ARTÍCULO</span><span>CATEGORÍA</span><span>STOCK</span><span>MÍNIMO</span><span>ESTADO</span></div>${items.map(i=>`<div class="table-row"><div class="item-name"><span class="item-icon"><i class="ph ${iconForCategory(i.category)}"></i></span><div><strong>${esc(i.name)}</strong><small>${esc(i.id)} · ${esc(i.location)}</small></div></div><span>${esc(i.category)}</span><strong>${i.stock} ${esc(i.unit)}</strong><span>${i.min}</span>${badge(status(i)==='ok'?'Disponible':status(i)==='low'?'Stock bajo':'Crítico',status(i))}</div>`).join('')}`}
function nextActions(o){if(o.status==='Solicitada')return `<button class="mini-btn" data-order-action="approve" data-id="${o.id}">Aprobar</button>`;if(o.status==='Aprobada')return `<button class="mini-btn" data-order-action="send" data-id="${o.id}">Preparar correo</button>`;if(o.status==='Enviada')return `<button class="mini-btn" data-order-action="receive" data-id="${o.id}">Recibir</button>`;return badge('Cerrada','ok')}
function renderOrders(){document.querySelector('#orders-table').innerHTML=`<div class="table-row orders header"><span>ORDEN</span><span>ARTÍCULO</span><span>PROVEEDOR</span><span>TOTAL</span><span>ESTADO</span><span>ACCIÓN CONTROLADA</span></div>${state.orders.map(o=>`<div class="table-row orders"><div><strong>${esc(o.id)}</strong><small>${new Date(o.createdAt).toLocaleDateString('es-CL')}</small></div><div><strong>${esc(o.item)}</strong><small>${o.quantity} unidades</small></div><span>${esc(o.supplier)}</span><strong>${money(o.total)}</strong>${badge(o.status,o.status==='Recibida'?'ok':o.status==='Solicitada'?'low':'pending')}<div class="row-actions">${nextActions(o)}</div></div>`).join('')}`}
function renderSuppliers(){document.querySelector('#suppliers-table').innerHTML=state.suppliers.map(s=>`<article class="supplier-card"><span class="card-icon"><i class="ph ph-buildings"></i></span><h3>${esc(s.name)}</h3><p>${esc(s.category)}<br>${esc(s.contact)}</p><div class="card-footer">${badge(s.status,s.status.toLowerCase().includes('pendiente')?'low':'pending')}<small>${esc(s.id)}</small></div></article>`).join('')}
function renderAudit(){document.querySelector('#audit-timeline').innerHTML=state.audit.map(e=>`<div class="event"><span class="event-icon"><i class="ph ph-${e.type==='Orden'?'shopping-cart-simple':e.type==='Inventario'?'cube':'shield-check'}"></i></span><div><strong>${esc(e.message)}</strong><p>${esc(e.detail)}</p><small>${esc(e.actor)} · origen: aplicación</small></div><time>${new Date(e.at).toLocaleString('es-CL')}</time></div>`).join('')}
function renderIntegrations(){document.querySelector('#integration-cards').innerHTML=(integrations.length?integrations:[{name:'Entorno Vercel',configured:false,detail:'No chequeado',icon:'ph-cloud'}]).map(x=>`<article class="integration-card"><span class="card-icon"><i class="ph ${x.icon||'ph-plug'}"></i></span><h3>${esc(x.name)}</h3><p>${esc(x.detail)}</p><div class="card-footer">${badge(x.configured?'Configurada':'Pendiente',x.configured?'ok':'low')}<small>Chequeo de entorno</small></div></article>`).join('')}
function renderAll(){renderMetrics();renderInventoryPreview();renderOrderProgress();renderIntegrationPreview();renderSupplierPreview();renderInventory();renderOrders();renderSuppliers();renderAudit();renderIntegrations();fillForms()}
function fillForms(){const s=document.querySelector('#order-supplier'),i=document.querySelector('#order-item');if(s)s.innerHTML=state.suppliers.map(x=>`<option>${esc(x.name)}</option>`).join('');if(i)i.innerHTML=state.inventory.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function checkIntegrations(){const icons={'Gmail':'ph-envelope-simple','Google Drive':'ph-google-drive-logo','Google Sheets':'ph-table','Persistencia':'ph-database','Vercel':'ph-cloud'};try{const res=await fetch('/api/integrations',{cache:'no-store'});if(!res.ok)throw new Error('Sin endpoint');const data=await res.json();integrations=data.integrations.map(x=>({...x,icon:icons[x.name]||'ph-plug'}));toast('Chequeo de integraciones actualizado')}catch{integrations=[{name:'Vercel',configured:location.hostname.endsWith('vercel.app'),detail:location.hostname.endsWith('vercel.app')?'Aplicación servida por Vercel':'Vista local',icon:'ph-cloud'},{name:'Gmail',configured:false,detail:'Variable OAuth no verificada',icon:'ph-envelope-simple'},{name:'Google Drive',configured:false,detail:'Variable OAuth no verificada',icon:'ph-google-drive-logo'},{name:'Google Sheets',configured:false,detail:'Identificadores no verificados',icon:'ph-table'},{name:'Persistencia',configured:false,detail:'Solo almacenamiento local demostrativo',icon:'ph-database'}]}renderIntegrationPreview();renderIntegrations()}
function orderAction(action,id){const o=state.orders.find(x=>x.id===id);if(!o)return;if(action==='approve'){if(!confirm(`Aprobar ${o.id} por ${money(o.total)}? Esta acción queda auditada.`))return;o.status='Aprobada';audit('Orden',`${o.id} aprobada`,`Aprobación humana · ${money(o.total)}`);toast('Orden aprobada con trazabilidad')}else if(action==='send'){const subject=encodeURIComponent(`Orden de compra ${o.id}`),body=encodeURIComponent(`Proveedor: ${o.supplier}\nArtículo: ${o.item}\nCantidad: ${o.quantity}\n\nSolicitud sujeta a documentación y confirmación.`);window.location.href=`mailto:?subject=${subject}&body=${body}`;o.status='Enviada';audit('Orden',`Correo preparado para ${o.id}`,'Se abrió el cliente de correo; envío efectivo pendiente de confirmación humana');toast('Borrador abierto; envío pendiente')}else if(action==='receive'){if(!confirm(`Confirmar recepción de ${o.quantity} unidades para ${o.id}?`))return;o.status='Recibida';const item=state.inventory.find(x=>x.id===o.itemId);if(item)item.stock+=o.quantity;audit('Inventario',`${o.id} recibida`,`${o.quantity} unidades incorporadas a ${o.item}`);toast('Recepción registrada e inventario actualizado')}save()}
function exportRows(filename,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)go(nav.dataset.view);const g=e.target.closest('[data-go]');if(g)go(g.dataset.go);if(e.target.closest('[data-open-order]'))document.querySelector('#order-dialog').showModal();const a=e.target.closest('[data-order-action]');if(a)orderAction(a.dataset.orderAction,a.dataset.id)});
document.querySelector('#menu-btn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('#refresh-btn').onclick=()=>{renderAll();checkIntegrations()};document.querySelector('#inventory-search').oninput=renderInventory;document.querySelector('#inventory-filter').onchange=renderInventory;document.querySelector('#check-integrations').onclick=checkIntegrations;
document.querySelector('#order-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),item=state.inventory.find(x=>x.id===fd.get('item')),qty=Number(fd.get('quantity')),cost=Number(fd.get('unitCost')),id=`OC-${String(state.orders.length+1).padStart(4,'0')}`;state.orders.unshift({id,supplier:fd.get('supplier'),item:item.name,itemId:item.id,quantity:qty,unitCost:cost,total:qty*cost,costCenter:fd.get('costCenter'),reason:fd.get('reason'),status:'Solicitada',createdAt:new Date().toISOString(),owner:'Claudia Celedón'});audit('Orden',`${id} solicitada`,`${qty} × ${item.name} · aprobación pendiente`);save();e.currentTarget.reset();document.querySelector('#order-dialog').close();toast('Solicitud registrada; aprobación pendiente')});
document.querySelector('#add-supplier').onclick=()=>document.querySelector('#supplier-dialog').showModal();document.querySelector('#supplier-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=`PRV-${String(state.suppliers.length+1).padStart(3,'0')}`;state.suppliers.push({id,name:fd.get('name'),contact:fd.get('contact'),category:fd.get('category'),status:'Pendiente documental'});audit('Proveedor',`${id} registrado`,'Validación documental pendiente');save();e.currentTarget.reset();document.querySelector('#supplier-dialog').close();toast('Proveedor registrado como pendiente')});
document.querySelector('#export-btn').onclick=()=>exportRows('novage_inventario_demo.csv',[['Código','Artículo','Categoría','Stock','Mínimo','Unidad','Ubicación'],...state.inventory.map(i=>[i.id,i.name,i.category,i.stock,i.min,i.unit,i.location])]);document.querySelector('#export-audit').onclick=()=>exportRows('novage_trazabilidad_demo.csv',[['Fecha','Tipo','Evento','Detalle','Actor'],...state.audit.map(a=>[a.at,a.type,a.message,a.detail,a.actor])]);
renderAll();go(location.hash.slice(1) in views?location.hash.slice(1):'inicio');checkIntegrations();
